Name:           ros-kinetic-rocon-app-manager
Version:        0.8.0
Release:        0%{?dist}
Summary:        ROS rocon_app_manager package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/rocon_app_manager
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-capabilities
Requires:       ros-kinetic-gateway-msgs
Requires:       ros-kinetic-rocon-app-manager-msgs
Requires:       ros-kinetic-rocon-app-utilities
Requires:       ros-kinetic-rocon-apps
Requires:       ros-kinetic-rocon-console
Requires:       ros-kinetic-rocon-gateway
Requires:       ros-kinetic-rocon-gateway-utils
Requires:       ros-kinetic-rocon-hub
Requires:       ros-kinetic-rocon-interactions
Requires:       ros-kinetic-rocon-master-info
Requires:       ros-kinetic-rocon-python-comms
Requires:       ros-kinetic-rocon-python-utils
Requires:       ros-kinetic-rocon-std-msgs
Requires:       ros-kinetic-rocon-uri
Requires:       ros-kinetic-roslib
Requires:       ros-kinetic-rosmaster
Requires:       ros-kinetic-rospy
Requires:       ros-kinetic-std-msgs
BuildRequires:  python-catkin_pkg
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-roslint
BuildRequires:  ros-kinetic-rostest

%description
The public interface and retaskable interface for a robot.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Tue Jun 21 2016 Daniel Stonier <d.stonier@gmail.com> - 0.8.0-0
- Autogenerated by Bloom

